spring.application.name=transaction-service

server.port=8084

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# Register localhost instead of machine hostname
eureka.instance.prefer-ip-address=true
eureka.instance.ip-address=127.0.0.1
eureka.instance.hostname=localhost

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/banking_db
spring.datasource.username=postgres
spring.datasource.password=P@ssw0rd
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.default_schema=transaction_schema

# Flyway
spring.flyway.enabled=true
spring.flyway.default-schema=transaction_schema
spring.flyway.schemas=transaction_schema

# Kafka
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer


# Actuator
management.endpoints.web.exposure.include=health,info,flyway
management.endpoint.health.show-details=always