spring.application.name=gateway

server.port=8080


# ==========================================
# Eureka
# ==========================================

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true


# ==========================================
# Actuator
# ==========================================

management.endpoints.web.exposure.include=health,info,gateway


# ==========================================
# Gateway Discovery
# ==========================================

spring.cloud.gateway.server.webflux.discovery.locator.enabled=true
spring.cloud.gateway.server.webflux.discovery.locator.lower-case-service-id=true


# ==========================================
# Gateway Routes
# ==========================================

spring.cloud.gateway.server.webflux.routes[0].id=customer-service
spring.cloud.gateway.server.webflux.routes[0].uri=lb://customer-service
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/customers/**


spring.cloud.gateway.server.webflux.routes[1].id=account-service
spring.cloud.gateway.server.webflux.routes[1].uri=lb://account-service
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/api/accounts/**

spring.cloud.gateway.server.webflux.routes[1].filters[0].name=RequestRateLimiter
spring.cloud.gateway.server.webflux.routes[1].filters[0].args.redis-rate-limiter.replenishRate=10
spring.cloud.gateway.server.webflux.routes[1].filters[0].args.redis-rate-limiter.burstCapacity=20
spring.cloud.gateway.server.webflux.routes[1].filters[0].args.key-resolver=#{@ipKeyResolver}

spring.cloud.gateway.server.webflux.routes[2].id=loan-service
spring.cloud.gateway.server.webflux.routes[2].uri=lb://loan-service
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/api/loans/**


spring.cloud.gateway.server.webflux.routes[3].id=transaction-service
spring.cloud.gateway.server.webflux.routes[3].uri=lb://transaction-service
spring.cloud.gateway.server.webflux.routes[3].predicates[0]=Path=/api/transactions/**



# ==========================================
# Redis
# ==========================================

spring.data.redis.host=localhost
spring.data.redis.port=6379

# ==========================================
# OAuth2 / JWT
# ==========================================

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8085/realms/banking-realm

# ==========================================
# CORS
# ==========================================

spring.cloud.gateway.server.webflux.globalcors.add-to-simple-url-handler-mapping=true

spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowedOrigins=http://localhost:5173
spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowedMethods=GET,POST,PUT,DELETE,OPTIONS
spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowedHeaders=*
spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowCredentials=true



# ==========================================
# AI SERVICE - Python FastAPI
# ==========================================

spring.cloud.gateway.server.webflux.routes[4].id=ai-service
spring.cloud.gateway.server.webflux.routes[4].uri=http://localhost:8000
spring.cloud.gateway.server.webflux.routes[4].predicates[0]=Path=/api/ai/**